version: "3.5"

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${NETWORK_IPV4_CIDR:-172.100.1.0/24}"
        - subnet: "${NETWORK_IPV6_CIDR:-2001:3984:3989::/64}"

volumes:
  pd-dnscrypt:
  pd-pihole:

services:
  pd_dnscrypt:
    image: jedisct1/dnscrypt-server:latest
    container_name: pd_dnscrypt
    networks:
      dns_net:
        ipv4_address: "${DNSCRYPT_IPV4_ADDR:-172.100.1.2}"
        ipv6_address: "${DNSCRYPT_IPV6_ADDR:-2001:3984:3989::10}"
    environment:
      TZ: "${TIMEZONE:-America/Chicago}"
    volumes:
      - pd-dnscrypt:/opt/encrypted-dns/etc/keys
    # First run
    #command: [ 'init', '-N', 'sylvis.net', '-E', '192.168.1.42:443' ]
    command: init -N sylvis.net -E 192.168.1.42:443
    # Subsequent runs can use the default 'start' command
    restart: unless-stopped

  pd_pihole:
    container_name: pd_pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: "${PIHOLE_IPV4_ADDR:-172.100.1.3}"
        ipv6_address: "${DNSCRYPT_IPV6_ADDR:-2001:3984:3989::20}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "80:80/tcp"
      #- "443:443/tcp"
    environment:
      TZ: "${TIMEZONE:-America/Chicago}"
      WEBPASSWORD: "${PIHOLE_WEB_ADMIN_PASSWORD:?}"
      PIHOLE_DNS_: "pd_dnscrypt#5353;${DNSCRYPT_IPV6_ADDR:-2001:3984:3989::20}#53530"
    dns:
      - 127.0.0.1
    volumes:
      - pd-pihole:/etc/pihole
      #- pd-pihole/config/dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
    depends_on:
      - pd_dnscrypt